//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C__OOP.model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C__OOP.model.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap sai, yeu cau nhap lai.
        /// </summary>
        internal static string ErrorGioiTinh {
            get {
                return ResourceManager.GetString("ErrorGioiTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap sai, yeu sau nhap lai.
        /// </summary>
        internal static string ErrorID {
            get {
                return ResourceManager.GetString("ErrorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap sai, yeu cau nhap lai.
        /// </summary>
        internal static string ErrorTen {
            get {
                return ResourceManager.GetString("ErrorTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap sai, yeu cau nhap lai.
        /// </summary>
        internal static string ErrorTuoi {
            get {
                return ResourceManager.GetString("ErrorTuoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap gioi tinh.
        /// </summary>
        internal static string InputGioiTinh {
            get {
                return ResourceManager.GetString("InputGioiTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ID.
        /// </summary>
        internal static string InputID {
            get {
                return ResourceManager.GetString("InputID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten.
        /// </summary>
        internal static string InputTen {
            get {
                return ResourceManager.GetString("InputTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap tuoi.
        /// </summary>
        internal static string InputTuoi {
            get {
                return ResourceManager.GetString("InputTuoi", resourceCulture);
            }
        }
    }
}
